import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col rounded-md">
        <main className=" flex flex-grow justify-center bg-gray-100 dark:bg-gray-900">
          {children}
        </main>
      </body>
    </html>
  )
}
